export enum ActionGroup {
  PRODUCT = 'PRODUCT',
  ADMIN = 'ADMIN',
  SALES = 'SALES',
  PURCHASING = 'PURCHASING',
  ACCOUNTING = 'ACCOUNTING',
  BANKING = 'BANKING',
  AUTH = 'AUTH',
}

export enum ActionType {
  ADMIN = 'ADMIN',
  DIRECTOR = 'DIRECTOR',
  MANAGER = 'MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  USER = 'USER',
  CUSTOMER = 'CUSTOMER',
  SUPPLIER = 'SUPPLIER',
}
